const ct={view:'table',dimension:'all',measure:'percent',color:true,search:'',sort:'source',direction:'desc'};
const tableGroups={gender:['female','male'],age:['young','middle','older'],near:['far','near']};
function overviewGuide(){return `<section class="overview-guide card" aria-labelledby="guide-title"><div class="guide-copy"><div class="eyebrow">Cómo aprovechar el estudio</div><h2 id="guide-title">Cuatro capas. Una lectura conectada.</h2><p>Empieza por una señal y abre las demás cuando necesites comprender su contexto, sus matices o sus diferencias.</p><div class="guide-recipes" aria-label="Combinaciones sugeridas"><span><b>Priorizar</b> Resultados + lenguaje</span><span><b>Segmentar</b> Resultados + cruces</span><span><b>Diseñar una respuesta</b> Cruces + territorio</span></div></div><div class="guide-path"><button data-open-q="q2"><i>01</i>${icon('questions')}<span><b>Qué aparece</b><small>Resultados y categorías</small></span></button><button data-guide="map"><i>02</i>${icon('findings')}<span><b>Cómo se expresa</b><small>Conceptos y respuestas</small></span></button><button data-deep-cross="q2|near|q2-44"><i>03</i>${icon('cross')}<span><b>Para quién cambia</b><small>Género, edad y cercanía</small></span></button><button data-go="territory"><i>04</i>${icon('territory')}<span><b>Dónde profundizar</b><small>Contexto territorial</small></span></button></div></section>`}
function tableDimensions(question){return Object.keys(tableGroups).filter(k=>question.id!=='q1'||k!=='near')}
function tableKeys(question){return ['total',...(ct.dimension==='all'?tableDimensions(question):[ct.dimension]).flatMap(k=>tableGroups[k])].filter(k=>k in question.n)}
function tableValue(row,key){return ct.measure==='difference'&&key!=='total'?100*(row.values[key]-row.values.total):100*row.values[key]}
function tableRows(question){const rows=question.rows.filter(r=>normalized(r.label).includes(normalized(ct.search.trim())));return ct.sort==='source'?rows:rows.sort((a,b)=>(tableValue(a,ct.sort)-tableValue(b,ct.sort))*(ct.direction==='asc'?1:-1))}
function signedPoints(value){const rounded=Math.round((value+Number.EPSILON)*10)/10;return `${rounded>0?'+':''}${fmt(Object.is(rounded,-0)?0:rounded,1)}`}
function cellStyle(row,key){if(!ct.color)return '';const value=tableValue(row,key);if(ct.measure==='difference'&&key!=='total')return `background:${value>=0?'rgba(69,186,178,':'rgba(190,143,72,'}${Math.min(.34,Math.abs(value)/40).toFixed(3)})`;return `background:rgba(110,189,151,${Math.min(.5,row.values[key]*.85).toFixed(3)})`}
function columnHeader(question,key){const active=ct.sort===key;return `<th scope="col" class="${key==='total'?'ct-total':''}" aria-sort="${active?(ct.direction==='desc'?'descending':'ascending'):'none'}"><button data-ct-sort="${key}" title="Ordenar por ${labels[key]}">${labels[key]}<span aria-hidden="true">${active?(ct.direction==='desc'?'↓':'↑'):'↕'}</span></button><small>n = ${question.n[key]}</small></th>`}
function tableBody(question){const keys=tableKeys(question),rows=tableRows(question);return rows.length?rows.map(row=>`<tr><th scope="row"><button data-ct-topic="${row.id}" title="Comparar ${esc(row.label)} en gráfico"><span>${esc(row.label)}</span><span class="ct-row-arrow" aria-hidden="true">↗</span></button></th>${keys.map(key=>`<td class="ct-number ${key==='total'?'ct-total':''}" style="${cellStyle(row,key)}" title="${esc(row.label)} · ${labels[key]}: ${pct(row.values[key],1)} · n = ${question.n[key]}${key!=='total'?` · Diferencia frente al total: ${signedPoints(100*(row.values[key]-row.values.total))} pp`:''}">${ct.measure==='difference'&&key!=='total'?signedPoints(tableValue(row,key)):pct(row.values[key],1)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${keys.length+1}"><div class="empty">No hay categorías con «${esc(ct.search)}». Prueba otro término o borra la búsqueda.</div></td></tr>`}
function tableLegend(){return ct.measure==='difference'?`<span class="ct-legend-item"><i class="ct-below"></i>Por debajo del total</span><span class="ct-legend-item"><i class="ct-above"></i>Por encima del total</span><span>Valores en puntos porcentuales (pp). El total conserva su %.</span>`:`<span class="ct-legend-item"><i class="ct-scale"></i>Mayor intensidad = mayor porcentaje</span><span>Porcentaje dentro de cada columna · Ponderado</span>`}
function classicTable(){const question=q(state.crossQ),dims=ct.dimension==='all'?tableDimensions(question):[ct.dimension],keys=tableKeys(question);return `<section class="card ct-card"><div class="ct-heading"><div class="eyebrow">${question.id.toUpperCase().replace('Q','P')} · ${question.kind}</div><h2 class="question-title">${question.text}</h2><div class="statline"><span class="pill green">${question.n.total} respuestas procesables</span><span class="pill" id="ct-count">${tableRows(question).length} de ${question.rows.length} ${question.id==='q1'?'alternativas':'categorías'}</span><span class="pill">${ct.measure==='difference'?'Diferencias frente al total · pp':'Porcentajes ponderados'}</span></div></div>
<div class="ct-toolbar"><div class="ct-filters"><label class="field">Columnas<select id="ct-dimension">${options([['all','Todos los cruces'],...tableDimensions(question).map(k=>[k,groupLabels[k]])],ct.dimension)}</select></label><label class="field">Mostrar<select id="ct-measure">${options([['percent','Porcentajes (%)'],['difference','Diferencia frente al total (pp)']],ct.measure)}</select></label><label class="field ct-search">Buscar categoría<input type="search" id="ct-search" placeholder="Ej. seguridad, áreas verdes…" value="${esc(ct.search)}"></label></div><div class="ct-actions"><label class="ct-check"><input type="checkbox" id="ct-color" ${ct.color?'checked':''}>Resaltar con color</label><button class="textbtn" data-ct-action="reset" ${ct.sort==='source'&&!ct.search?'disabled':''}>Restablecer orden y búsqueda</button><div class="ct-export"><button class="btn" data-ct-action="export">${icon('download')}Descargar CSV</button><button class="btn" data-ct-action="print">Imprimir / PDF</button></div></div></div>
<div class="ct-reading"><span>Ordena con los encabezados · Abre el gráfico desde una categoría</span><span class="ct-scrollhint">Desliza la tabla para ver más columnas →</span></div><div class="ct-tablewrap" tabindex="0" role="region" aria-label="Tabla de cruces, desplazable" aria-describedby="ct-table-note"><table class="ct-table ${ct.dimension!=='all'?'ct-compact':''}"><caption class="sr-only">${question.id.toUpperCase().replace('Q','P')}. ${question.text} ${ct.measure==='difference'?'Diferencias frente al total en puntos porcentuales.':'Porcentajes ponderados por columna.'} Bases sin ponderar.</caption><thead><tr class="ct-groups"><th scope="col" rowspan="2">${question.id==='q1'?'Respuesta':'Categoría semántica'}<small>Base por columna ↓</small></th><th scope="colgroup">Estudio</th>${dims.map(k=>`<th scope="colgroup" colspan="${tableGroups[k].length}">${groupLabels[k]}</th>`).join('')}</tr><tr class="ct-columns">${keys.map(k=>columnHeader(question,k)).join('')}</tr></thead><tbody id="ct-body">${tableBody(question)}</tbody><tfoot><tr><th scope="row">Base sin ponderar · n</th>${keys.map(k=>`<td class="${k==='total'?'ct-total':''}">${question.n[k]}</td>`).join('')}</tr></tfoot></table></div>
<div class="ct-notes"><div class="ct-legend ${!ct.color?'ct-no-color':''}">${tableLegend()}</div><p class="caption" id="ct-table-note">${baseNote(question)} Las bases n cuentan personas con respuesta procesable, sin ponderar. Las bases por género o edad pueden sumar menos que el total por falta de ese dato.</p>${ct.measure==='difference'?'<p class="caption">Diferencia = porcentaje del segmento − porcentaje total. Se calcula antes de redondear. Es una comparación descriptiva; el color no indica significación estadística.</p>':''}<p class="meta">Cada dimensión se cruza por separado. Las columnas no combinan género, edad y cercanía entre sí.</p>${source(question)}</div></section>`}
function chartColor(i){return ['#79E2A6','#45BAB2','#F0B96A'][i%3]}
function gapRows(question,keys){return question.rows.map(row=>{const ordered=[...keys].sort((a,b)=>row.values[a]-row.values[b]);return {row,min:ordered[0],max:ordered.at(-1),gap:100*(row.values[ordered.at(-1)]-row.values[ordered[0]])}}).sort((a,b)=>b.gap-a.gap).slice(0,6)}
function ringChart(question,topic,keys){return `<div class="ct-rings" role="img" aria-label="Comparación de ${esc(topic.label)}: ${keys.map(k=>`${labels[k]} ${pct(topic.values[k],1)}`).join(', ')}">${keys.map((key,i)=>{const value=100*topic.values[key];return `<article class="ct-ring-card ${topic.values[key]===Math.max(...keys.map(k=>topic.values[k]))?'is-high':''}" style="--ring:${chartColor(i)};--ring-offset:${100-value};--ring-delay:${i*.11}s"><div class="ct-ring"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="ct-ring-bg" cx="60" cy="60" r="48" pathLength="100"/><circle class="ct-ring-progress" cx="60" cy="60" r="48" pathLength="100"/></svg><strong>${pct(topic.values[key],1)}</strong></div><h3>${labels[key]}</h3><span>n = ${question.n[key]}</span></article>`}).join('')}</div>`}
function gapMap(question,keys){return `<section class="ct-gap-map"><div class="ct-section-head"><div><div class="eyebrow">Dónde cambia más la lectura</div><h2>Contrastes para explorar</h2></div><p>Las seis categorías con mayor distancia entre los grupos seleccionados.</p></div><div class="ct-gap-grid">${gapRows(question,keys).map(({row,min,max,gap})=>`<button data-select-topic="${row.id}" class="${row.id===state.topic?'active':''}"><span class="ct-gap-label">${esc(row.label)}</span><span class="ct-gap-track" aria-hidden="true"><i style="left:${row.values[min]*100}%"></i><i style="left:${row.values[max]*100}%"></i><em style="left:${row.values[min]*100}%;width:${(row.values[max]-row.values[min])*100}%"></em></span><span class="ct-gap-value">${fmt(gap,1)} pp</span><small>${labels[min]} ${pct(row.values[min],1)} · ${labels[max]} ${pct(row.values[max],1)}</small></button>`).join('')}</div><p class="caption">Orden descriptivo dentro de esta pregunta. Selecciona una categoría para llevarla al gráfico.</p></section>`}
function visualComparisonPanel(){const question=q(state.crossQ),keys=groups[state.dim],topic=question.rows.find(v=>v.id===state.topic)||question.rows[0],ordered=[...keys].sort((a,b)=>topic.values[a]-topic.values[b]),minKey=ordered[0],maxKey=ordered.at(-1),gap=100*(topic.values[maxKey]-topic.values[minKey]);return `<section class="ct-chart-card"><div class="ct-chart-head"><div><div class="eyebrow">${question.id.toUpperCase().replace('Q','P')} · Lectura visual</div><h2>${esc(topic.label)}</h2><p>${esc(question.text)}</p></div><div class="ct-chart-controls"><label class="field">Comparar por<select id="cross-dim">${Object.entries(groupLabels).filter(([k])=>question.id!=='q1'||k!=='near').map(([k,l])=>`<option value="${k}" ${k===state.dim?'selected':''}>${l}</option>`).join('')}</select></label><label class="field">Idea o respuesta<select id="cross-topic">${question.rows.map(v=>`<option value="${v.id}" ${v.id===topic.id?'selected':''}>${v.label}</option>`).join('')}</select></label><button class="btn" data-ct-action="replay" aria-label="Repetir animación">Repetir</button></div></div><div class="ct-chart-stage"><div class="ct-chart-visual">${ringChart(question,topic,keys)}<div class="ct-total-line"><span>Total del estudio</span><b>${pct(topic.values.total,1)}</b><small>n = ${question.n.total}</small></div></div><aside class="ct-chart-insight"><div class="eyebrow">Diferencia visible</div><strong>${fmt(gap,1)}<small>pp</small></strong><p>${gap>.05?`Entre ${labels[maxKey].toLowerCase()} y ${labels[minKey].toLowerCase()}.`:'Los grupos muestran valores prácticamente iguales.'}</p><div class="ct-extremes"><span><i style="background:${chartColor(keys.indexOf(maxKey))}"></i>${labels[maxKey]} <b>${pct(topic.values[maxKey],1)}</b></span><span><i style="background:${chartColor(keys.indexOf(minKey))}"></i>${labels[minKey]} <b>${pct(topic.values[minKey],1)}</b></span></div><small>Comparación descriptiva. No prueba causalidad ni significación estadística.</small></aside></div><div class="ct-chart-source">${source(question)}</div></section>${gapMap(question,keys)}`}
function cross(){return `<div class="ct-view ${ct.view==='table'?'ct-table-view':''}">${intro('Segmentos','La misma pregunta, distintas lecturas.','Elige una idea y compárala por género, edad o cercanía. La tabla entrega precisión; el gráfico hace visible la diferencia.')}<div class="ct-view-switch" role="group" aria-label="Vista de cruces"><button data-ct-view="table" class="${ct.view==='table'?'active':''}" aria-pressed="${ct.view==='table'}">Tabla completa</button><button data-ct-view="chart" class="${ct.view==='chart'?'active':''}" aria-pressed="${ct.view==='chart'}">Lectura visual</button></div>${questionTabs(state.crossQ,'cross-q')}${ct.view==='table'?classicTable():visualComparisonPanel()}</div>`}
function exportCrosstab(){const question=q(state.crossQ),keys=tableKeys(question);const rows=[['TITANIA Pulse · Comuna Delta · Caso anonimizado'],['Pregunta',question.id.toUpperCase().replace('Q','P'),question.text],['Fuente',D.sources.tables,question.range,'Informe pp. '+question.pages.join(', ')],['Medida',ct.measure==='difference'?'Diferencia en puntos porcentuales: segmento menos total. La columna Total conserva su porcentaje.':'Porcentajes ponderados dentro de cada columna'],['Lectura',baseNote(question)],['Bases','n sin ponderar. Los segmentos con dato pueden sumar menos que el total.'],['Alcance','Cada dimensión es independiente. No combina segmentos ni calcula significación estadística.'],['Selección',ct.dimension==='all'?'Todos los cruces':groupLabels[ct.dimension],'Búsqueda',ct.search||'Sin filtro'],['Orden',ct.sort==='source'?'Orden del estudio':labels[ct.sort],ct.sort==='source'?'':ct.direction==='desc'?'Descendente':'Ascendente'],[],['Dimensión','Estudio',...(ct.dimension==='all'?tableDimensions(question):[ct.dimension]).flatMap(k=>tableGroups[k].map(()=>groupLabels[k]))],['Categoría',...keys.map(k=>labels[k])],['Base n',...keys.map(k=>question.n[k])],...tableRows(question).map(row=>[row.label,...keys.map(k=>tableValue(row,k).toFixed(4).replace('.',','))])];
// Numeric cells stay numeric in Spanish Excel; formula protection applies to text only.
const safe=value=>{const s=String(value??'');return '"'+(/^[=+@-]/.test(s)&&!/^[-+]?\d+(?:[.,]\d+)?$/.test(s)?"'"+s:s).replace(/"/g,'""')+'"'};
download(`TITANIA_Pulse_${question.id}_cruces_${ct.dimension}_${ct.measure}.csv`,'\uFEFF'+rows.map(row=>row.map(safe).join(';')).join('\r\n'),'text/csv;charset=utf-8');toast('Tabla descargada con las columnas, filas y orden visibles.')}
document.addEventListener('click',event=>{const e=event.target.closest('[data-ct-view],[data-ct-sort],[data-ct-topic],[data-ct-action]');if(!e)return;
if(e.dataset.ctView){ct.view=e.dataset.ctView;render()}
else if(e.dataset.ctSort){if(ct.sort===e.dataset.ctSort)ct.direction=ct.direction==='desc'?'asc':'desc';else{ct.sort=e.dataset.ctSort;ct.direction='desc'}const x=document.querySelector('.ct-tablewrap')?.scrollLeft||0;render();document.querySelector('.ct-tablewrap').scrollLeft=x;document.querySelector(`[data-ct-sort="${ct.sort}"]`).focus({preventScroll:true})}
else if(e.dataset.ctTopic){state.topic=e.dataset.ctTopic;ct.view='chart';if(ct.dimension!=='all')state.dim=ct.dimension;if(state.crossQ==='q1'&&state.dim==='near')state.dim='age';render();window.scrollTo({top:0,behavior:'smooth'})}
else if(e.dataset.ctAction==='reset'){ct.sort='source';ct.direction='desc';ct.search='';render()}
else if(e.dataset.ctAction==='export'){exportCrosstab()}
else if(e.dataset.ctAction==='print'){window.print()}
else if(e.dataset.ctAction==='replay'){document.querySelectorAll('.ct-ring-progress').forEach(ring=>{ring.style.animation='none';void ring.getBoundingClientRect();ring.style.animation=''})}
});
document.addEventListener('click',event=>{const e=event.target.closest('[data-guide]');if(!e)return;ex.panel=e.dataset.guide;go('questions')});
document.addEventListener('change',event=>{const e=event.target;if(e.id==='ct-dimension'){ct.dimension=e.value;if(!tableKeys(q(state.crossQ)).includes(ct.sort))ct.sort='source';render()}else if(e.id==='ct-measure'){ct.measure=e.value;render()}else if(e.id==='ct-color'){ct.color=e.checked;render()}});
document.addEventListener('input',event=>{if(event.target.id!=='ct-search')return;ct.search=event.target.value;const question=q(state.crossQ);$('ct-body').innerHTML=tableBody(question);$('ct-count').textContent=`${tableRows(question).length} de ${question.rows.length} ${question.id==='q1'?'alternativas':'categorías'}`;document.querySelector('[data-ct-action="reset"]').disabled=ct.sort==='source'&&!ct.search;});
